name: app_coleta_seletiva
description: Um aplicativo de auxílio a coleta seletiva.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  mocktail: ^0.3.0
  firebase: ^9.0.3
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - lib/app/imagens/fundo.png
    - lib/app/imagens/logo.png
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

