name: app_coleta_seletiva
description: Um aplicativo de auxílio a coleta seletiva.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  mocktail: ^0.3.0
  firebase: ^9.0.3
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.1.0
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - lib/app/imagens/fundo.png
    - lib/app/imagens/logo.png
    - lib/app/imagens/top_header.png
    - lib/app/imagens/cupom.png
    - lib/app/imagens/+.png
    - lib/app/imagens/-.png
    - lib/app/imagens/99.jpeg
    - lib/app/imagens/ajuda.png
    - lib/app/imagens/americanas.png
    - lib/app/imagens/caminhao.png
    - lib/app/imagens/cinemark.png
    - lib/app/imagens/Dicas.png
    - lib/app/imagens/dropdown.png
    - lib/app/imagens/editar_usuario.png
    - lib/app/imagens/email.png
    - lib/app/imagens/fundo2.png
    - lib/app/imagens/fundo3.png
    - lib/app/imagens/garrafa.png
    - lib/app/imagens/hbo.jpg
    - lib/app/imagens/ifood.png
    - lib/app/imagens/Historico.png
    - lib/app/imagens/logo2.png
    - lib/app/imagens/logo3.png
    - lib/app/imagens/movida.jpg
    - lib/app/imagens/Sair.png
    - lib/app/imagens/solicitacoes.png
    - lib/app/imagens/solicitar_coleta.png
    - lib/app/imagens/Tela_Cadastro.png
    - lib/app/imagens/Tela_Inicial.png
    - lib/app/imagens/telefone.png
    - lib/app/imagens/top_header.png
    - lib/app/imagens/traco.png
    - lib/app/imagens/uber.png
    - lib/app/imagens/Usuario.png
    - lib/app/imagens/voltar.png
    - lib/app/imagens/wpp.png
    - lib/app/imagens/ze_delivery.png

  fonts:
    - family: Montserrat Medium
      fonts:
        - asset: lib/app/fonts/mo_me.ttf

    - family: Montserrat Regular
      fonts:
        - asset: lib/app/fonts/mo_re.ttf

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

